export const VIDEO_LENGTH_SECONDS_LIMIT = 60; // 15 sec is the maximum allowed for a video upload (in seconds)
export const IMAGE_SIZE_LIMIT_MB = 5; // 5 MB limit for image upload (this is the limit from the AI tool)
export const VIDEO_SIZE_LIMIT_MB = 100; // 20 MB limit for image upload
export const MAX_FREE_SCANS = 3;
export const MAX_DAILY_ACTIVITIES = 7;
export const MAX_SCANS_FOR_FREE = 2;
export const MAX_AI_COACH_CONVERSATIONS_FOR_FREE = 1;
export const MAX_EXCUSE_BUSTER_CONVERSATIONS_FOR_FREE = 1;
export const TOTAL_ACTIVITIES_PER_WEEK_FOR_FREE = 5;
